project_id = "kmpjhtpuuwqkvfzomjnf"

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.validate-mercadopago]
verify_jwt = false

[functions.get-public-wedding]
verify_jwt = false